version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/php:8.1-browsers # The primary container where steps are run
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWD
          MYSQL_DATABASE: practice
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: passw0rd

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u $MYSQL_USER -ppassw0rd practice < app/sql/init.sql
            mysql -h 127.0.0.1 -u $MYSQL_USER -ppassw0rd --execute="SELECT * FROM practice.workouts"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build